import { AdminPageHeader, EmptyState } from "@/components/admin/AdminUi";
import { LifecycleStatusForm, ProjectAndServiceForms } from "@/components/admin/WorkspaceForms";
import { requireAdmin } from "@/lib/admin/auth";
import { formatCurrency, formatDate, formatStage } from "@/lib/admin/format";

export default async function ProjectsPage() {
  const { supabase } = await requireAdmin();
  const [firms, contacts, opportunities, projects, services] = await Promise.all([supabase.from("firms").select("id,name").order("name"), supabase.from("contacts").select("id,firm_id,full_name,email").order("full_name"), supabase.from("opportunities").select("id,firm_id,contact_id,title").order("updated_at", { ascending: false }), supabase.from("projects").select("id,firm_id,name,status,budget,start_date,target_completion_date,project_url,firms(name)").order("updated_at", { ascending: false }), supabase.from("service_subscriptions").select("id,firm_id,project_id,service_type,status,billing_interval,amount,currency,starts_on,renews_on,firms(name),projects(name)").order("updated_at", { ascending: false })]);
  return <main id="main-content"><AdminPageHeader title="Projects & services" description="Carry won work through onboarding and delivery, then retain the relationship through hosting, maintenance, visibility, and support." /><div className="mx-auto max-w-[1440px] space-y-12 px-5 py-8 sm:px-8 lg:px-10"><ProjectAndServiceForms firms={firms.data || []} contacts={contacts.data || []} opportunities={opportunities.data || []} projects={(projects.data || []).map(({ id, firm_id, name }) => ({ id, firm_id, name }))} /><section><div className="border-b border-[#9f9d96] pb-4"><h2 className="text-xl font-semibold">Delivery portfolio</h2></div>{projects.data?.length ? <div className="divide-y divide-[#cbc6bc]">{projects.data.map((project) => <article key={project.id} className="grid gap-4 py-5 md:grid-cols-[1.2fr_.8fr_.8fr_1.5fr] md:items-end"><div><strong>{project.name}</strong><p className="mt-1 text-sm text-[#686761]">{(project.firms as unknown as { name: string } | null)?.name}</p></div><span className="text-sm">{formatCurrency(Number(project.budget || 0))}</span><span className="text-sm text-[#686761]">{formatDate(project.start_date)} → {formatDate(project.target_completion_date)}</span><LifecycleStatusForm entity="project" id={project.id} value={project.status} options={["onboarding","active","blocked","completed","cancelled"]} /></article>)}</div> : <EmptyState title="No projects yet" body="A won opportunity can be opened as a tracked delivery engagement above." />}</section><section id="service-ledger" className="scroll-mt-6"><div className="border-b border-[#9f9d96] pb-4"><h2 className="text-xl font-semibold">Recurring service ledger</h2></div>{services.data?.length ? <div className="divide-y divide-[#cbc6bc]">{services.data.map((service) => <article key={service.id} className="grid gap-4 py-5 md:grid-cols-[1.1fr_1fr_.8fr_1.5fr] md:items-end"><div><strong>{formatStage(service.service_type)}</strong><p className="mt-1 text-sm text-[#686761]">{(service.firms as unknown as { name: string } | null)?.name}</p></div><span className="text-sm font-semibold">{formatCurrency(Number(service.amount), service.currency)} / {service.billing_interval}</span><span className="text-sm text-[#686761]">Renews {formatDate(service.renews_on)}</span><LifecycleStatusForm entity="service" id={service.id} value={service.status} options={["proposed","active","paused","cancelled","ended"]} /></article>)}</div> : <EmptyState title="No recurring services" body="Add hosting, maintenance, SEO or support retainers above to track recurring revenue and renewal dates." />}</section></div></main>;
}
